services:
  db:
    image: postgres
    container_name: db
    restart: always #container reinicia se morrer
    ports:
      - 5433:5432
    env_file:
      - ./hotel-back-end/.env.test #configurar POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB
    volumes:
    - pg:/var/lib/postgresql/data # onde os dados do postgres ficam armazenados no sistema operacional

  api:
    container_name: api
    build: ./hotel-back-end #Dockerfile do node se encontra na pasta atual
    ports:
      - 4000:4000
    depends_on:
      - db # sรณ sobe quando o postgres tiver no ar
    env_file:
      - ./hotel-back-end/.env.test #configurar DATABASE_URL

volumes:
  pg: # volume para os postgres
